---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: airflow
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13.0
        imagePullPolicy: IfNotPresent
        env: 
          - name: POSTGRES_DB
            value: "airflow"
          - name: POSTGRES_USER
            value: "airflow"
          - name: POSTGRES_PASSWORD
            value: "airflow1234"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432  
