---
apiVersion: v1
kind: Service
metadata:
  name: airflow-redis
  namespace: airflow
spec:
  selector:
    app: airflow-redis
  ports:
  - port: 6379
    targetPort: 6379

---
apiVersion: apps/v1 #1
kind: Deployment
metadata:
  name: airflow-redis
spec:
  selector:
    matchLabels:
      app: airflow-redis
      role: master
  replicas: 1
  template:
    metadata:
      labels:
        app: airflow-redis
        role: master
        tier: backend
    spec:
      containers:
      - name: master
        image: redis:5.0.6 # or just image: redis
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
