#apiVersion: v1
#kind: Service
#metadata:
#  name: airflow-webserver
#  namespace: airflow
#spec:
#  selector:
#    app: airflow-webserver
#  type: clusterIp
#  ports:
#  - name: http
#    port: 80
#    targetPort: 8080
#    protocol: TCP 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-webserver
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-webserver
  template:
    metadata:
      labels:
        app: airflow-webserver
        tier: frontend
    spec:
      volumes:
        - name: airflow-storage
          persistentVolumeClaim:
            claimName: airflow-pv-webserver
      securityContext:
        runAsUser: 50000
        fsGroup: 0
      containers:
      - name: airflow-webserver
        image: apache/airflow:2.2.4
        imagePullPolicy: IfNotPresent
        command: ["airflow"]
        args: ["webserver"]
        envFrom:
          - configMapRef:
              name: airflow-config
        volumeMounts:
        - mountPath: "/opt/airflow/"
          name: airflow-storage
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "1Gi"
  %                        
