apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config
  namespace: airflow
data:
  AIRFLOW__CORE__EXECUTOR: "CeleryExecutor"
  AIRFLOW__CORE__FERNET_KEY: "
  AIRFLOW__CORE__LOAD_EXAMPLES: "False"
  AIRFLOW__WEBSERVER__BASE_URL: <"https://to_define">
  AIRFLOW__WEBSERVER__WEB_SERVER_HOST: "0.0.0.0"
  AIRFLOW__WEBSERVER__WEB_SERVER_PORT: "8080"
  AIRFLOW__WEBSERVER__SECRET_KEY: 
  AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: "300"
  AIRFLOW__WEBSERVER__AUTHENTICATE: "True"
  AIRFLOW__WEBSERVER__AUTH_BACKEND: "airflow.contrib.auth.backends.github_enterprise_auth"
  AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX: "True"
  AIRFLOW__GITHUB_ENTERPRISE__HOST: "github.com"
  AIRFLOW__GITHUB_ENTERPRISE__OAUTH_CALLBACK_ROUTE: "/oauth/callback"
  AIRFLOW__GITHUB_ENTERPRISE__CLIENT_ID: "<to_define>"
  AIRFLOW__GITHUB_ENTERPRISE__CLIENT_SECRET: 
  AIRFLOW__GITHUB_ENTERPRISE__ALLOWED_TEAMS: 
  AIRFLOW__SMTP__SMTP_HOST: 
  AIRFLOW__SMTP__SMTP_PORT: "587"
  AIRFLOW__SMTP__SMTP_STARTTLS: "False"
  AIRFLOW__SMTP__SMTP_MAIL_FROM: 
  AIRFLOW__SMTP__SMTP_USER: 
  AIRFLOW__SMTP__SMTP_PASSWORD: 
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://airflow:airflow1234@postgres/airflow"
  AIRFLOW__CELERY__RESULT_BACKEND: "db+postgresql://airflow:airflow1234@postgres/airflow"
  AIRFLOW__CELERY__BROKER_URL: "redis://airflow-redis:6379/0"
