---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: slow
provisioner: k8s.io/minikube-hostpath
parameters:
  type: pd-standard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-pv-webserver
  namespace: airflow
spec:
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-pv-scheduler
  namespace: airflow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-pv-worker
  namespace: airflow
spec:
  storageClassName: slow
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-pv-reports
  namespace: airflow
spec:
  accessModes: 
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
