---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: airflow-worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: airflow-worker
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50%    
